Base api
driuzzo/cypress-faq pull request #12
Opened 2024-08-09 21:06 UTC by GiovaniRSantos

- Utilização de app actions para centralizar métodos que serão reutilizados na feature
- Exemplos de testes cobrindo um CRUD
- Métodos genéricos para abranger responsabilidades e reutilização em todas as features
- Documentação dos métodos utilizando a interface Chainable
- Utilização de typescript para um melhor desenvolvimento

2024-08-13 12:18 UTC, leolpc21 requested changes
coloquei algumas observações.

2024-08-13 12:18 UTC, leolpc21 commented on projetos/apiTests/cypress/support/jsonActions.ts
> +    createPost(itle: string, body: string, user_id: number)
o parametro title está incorreto, está como "itle"

2024-08-13 12:18 UTC, leolpc21 commented on projetos/apiTests/cypress/support/jsonActions.ts
> +
se está usando apenas o userId e id nas proximas requisições, não vejo sentido de extrair os dados de title e body aqui.

2024-08-13 12:18 UTC, leolpc21 commented on projetos/apiTests/cypress/support/jsonActions.ts
> +
remover espaços desnecessários

2024-08-13 12:18 UTC, leolpc21 commented on projetos/apiTests/cypress/support/jsonActions.ts
> +
remover espaços desnecessários

2024-08-13 12:18 UTC, leolpc21 commented on projetos/apiTests/cypress/support/app.ts
> +
remover espaços desnecessários

2024-08-13 12:18 UTC, leolpc21 commented on projetos/apiTests/cypress/support/app.ts
> +
remover espaços desnecessários

2024-08-13 12:18 UTC, leolpc21 commented on projetos/apiTests/cypress/support/app.ts
> +
remover espaços desnecessários

2024-08-13 12:18 UTC, leolpc21 commented on projetos/apiTests/cypress/support/app.ts
> +
remover espaços desnecessários

2024-08-13 21:35 UTC, GiovaniRSantos commented on projetos/apiTests/cypress/support/jsonActions.ts
> +    createPost(itle: string, body: string, user_id: number)
Vou ajustar! Obrigado.

2024-08-14 00:34 UTC, GiovaniRSantos commented
@leolpc21 feito alguns ajustes, pode validar novamente?

2024-08-16 18:55 UTC, leolpc21 approved these changes

2024-08-19 21:39 UTC, driuzzo approved these changes
@all-contributors please add @GiovaniRSantos for code

2024-08-19 21:40 UTC, merged