How to deal with multiple environment
driuzzo/cypress-faq pull request #9
Opened 2024-06-05 01:30 UTC by JarDeVSon

2024-06-05 14:31 UTC, driuzzo requested changes
Sugestão de alteração no arquivo README.md

2024-06-05 14:31 UTC, driuzzo commented on README.md
> +### Benefícios
Acredito que esse texto não seja necessário, pois a ideia do FAQ é postar a solução de forma mais direta.

2024-06-05 14:31 UTC, driuzzo commented on README.md
> +Ao desenvolver aplicações web, é crucial garantir que seu código funcione corretamente em diferentes ambientes (desenvolvimento, homologação e produção). O Cypress oferece uma maneira flexível de lid
Sugestão de texto:

"Para rodar o mesmo projeto em ambientes diferentes, você pode configurar uma baseUrl e depois apontar o ambiente desejado ao rodar os scripts via linha de comando."

2024-06-05 14:42 UTC, JarDeVSon commented on README.md
> +### Benefícios
De acordo

2024-06-05 14:42 UTC, JarDeVSon commented on README.md
> +Ao desenvolver aplicações web, é crucial garantir que seu código funcione corretamente em diferentes ambientes (desenvolvimento, homologação e produção). O Cypress oferece uma maneira flexível de lid
De acordo

2024-06-06 01:49 UTC, JarDeVSon reviewed
ajustes propostos

2024-06-06 11:04 UTC, driuzzo approved these changes
Aprovado.

2024-06-06 11:05 UTC, merged

2024-06-06 11:07 UTC, driuzzo commented
@all-contributors please add @JarDeVSon for code